Hongik_festival/festival/bars/urls.py
from django.urls import path
from . import views


app_name = 'bars'
urlpatterns = [
    path('', views.bar_list, name='bar_list'),
    path('<int:bar_id>/detail/', views.bar_detail, name='bar_detail'),
    path('<int:bar_id>/likes/', views.bar_like, name='bar_like'),
]

Hongik_festival/festival/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts import views


urlpatterns = [
    path('', views.index_return, name='index'),
    path('bars/', include('bars.urls', namespace='bars')), 
    path('posts/', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hongik_festival/festival/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('myposts/', views.my_post_list, name='my_post_list'),
    path('detail/<int:post_id>/',views.post_detail,name='detail'), # 글 자세히 보기
    path('new/',views.post_new,name="new"), # 글 쓰기
    path('<int:post_id>/delete/',views.post_delete, name="delete"), # 글 삭제
    path('<int:post_id>/update/',views.post_update, name="update"),
    path('<int:post_id>/comments/', views.post_comment_create, name='post_comment_create'), # 덧글 생성
    path('comments/<int:comment_id>/', views.post_comment_delete, name='post_comment_delete'), # 덧글 삭제
]

Hongik_festival/festival/posts/models.py
from django.conf import settings
from django.db import models


class TimeStampedModel(models.Model):
    """Base Model"""
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(TimeStampedModel):
    """ Post Model """
    title = models.CharField(max_length=140)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        null=True, 
        related_name='posts'
        )
    image = models.ImageField(upload_to='posts', blank=True, null=True)
    text = models.TextField(max_length=200)
    how_many = models.IntegerField(default=1) # 몇대몇 미팅을 구하는지 인원수 
    
    @property
    def comment_count(self):
        return self.comments.count()

    def __str__(self):
        return f'{self.title}-{self.creator}'

    class Meta:
        ordering = ['-created_at']

        
class Comment(TimeStampedModel):
    """ Comment Model """
    post = models.ForeignKey(
        Post, 
        on_delete=models.CASCADE, 
        null=True, 
        related_name='comments'
    )
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_DEFAULT,
        null=True,
        default='알수없음',
    )
    message = models.TextField()
    
    def __str__(self):
        return f'{self.post}-{self.creator}'

    class Meta:
        ordering = ['-created_at']    
        
        

Hongik_festival/festival/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment


def post_list(request):
    posts = Post.objects.all()
    search = request.GET.get('search', '')
    if search:
        posts = posts.filter(how_many=search)

    paginator = Paginator(posts, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'post_list.html', {'posts':posts, 'search':search})

@login_required
def my_post_list(request):
    posts = Post.objects.filter(creator=request.user)
    return render(request, 'my_post_list.html', {'posts':posts})
    
@login_required
def post_detail(request, post_id):
    post_detail = get_object_or_404(Post, id=post_id)
    request_user = request.user
    comments = post_detail.comments.all()
    return render(request, 'post_detail.html',{'post':post_detail, 'user':request_user, 'comments':comments})

# def post_new(request):
#     post = Post()
#     post.title = "admin12345"
#     return render(request,'post_new.html',{'post':post})

# def post_create(request):
#     user = request.user
#     if user.is_authenticated:
        # post= Post()
        # post.title = request.GET['title'] # 제목저장
        # post.text = request.GET['text'] # 본문저장
        # post.how_many = request.GET['how_many'] # 몇명 저장
        # post.creator = user #유저 정보 저장
        # post.save()
        # return redirect('/posts/detail/' + str(post.id))
    # else:
    #     return render(request, 'login.html')

@login_required
def post_new(request):
    user = request.user
    if request.method == 'GET':
        return render(request,'post_new.html')
    elif request.method == 'POST' and user.is_authenticated:
        post= Post()
        post.title = request.POST['title'] # 제목저장
        post.text = request.POST['text'] # 본문저장
        post.how_many = request.POST['how_many'] # 몇명 저장
        post.creator = user #유저 정보 저장
        post.save()
        return redirect('/posts/detail/' + str(post.id))
    else:
        return render(request, 'login.html')      

@login_required
def post_delete(request, post_id):
    post_to_delete = get_object_or_404(Post, pk=post_id)
    post_to_delete.delete()
    return redirect('/posts/myposts/')

# def post_update(request,post_id):
#     post = get_object_or_404(Post, pk = post_id)
#     return render(request,'post_new.html',{'post':post})

# def post_update_func(request,post_id):
#     post = get_object_or_404(Post, pk = post_id)
#     post.title = request.GET['title'] # 제목저장
#     post.text = request.GET['text'] # 본문저장
#     post.how_many = request.GET['how_many'] # 몇명 저장
#     post.creator = request.user #유저 정보 저장
#     post.save()
#     return redirect('/posts/detail/' + str(post.id))
# 조원준 : 끝

@login_required
def post_update(request, post_id):
    user = request.user
    if request.method == 'GET':
        post = get_object_or_404(Post, id = post_id)
        return render(request,'post_new.html', {'post':post})
    elif request.method == 'POST':
        post = get_object_or_404(Post, id=post_id)
        post.title = request.POST['title']
        post.text = request.POST['text']
        post.how_many = request.POST['how_many']
        post.creator = request.user
        post.save()
        return redirect('/posts/detail/' + str(post.id))
 
@login_required
def post_comment_create(request, post_id):
    user = request.user
    if request.method=='POST' and user.is_authenticated:
        post = get_object_or_404(Post, id=post_id)
        comment = Comment()
        comment.post = post
        comment.creator = user
        comment.message = request.POST['message']
        comment.save()
        return redirect('/posts/detail/' + str(post.id))
    else:
        return render(request, 'login.html')

@login_required
def post_comment_delete(request, comment_id):
    comment_to_delete = get_object_or_404(Comment, id=comment_id)
    post_id = comment_to_delete.post.id
    comment_to_delete.delete()
    return redirect('/posts/detail/' + str(post_id))

def index_return(request):
    return render(request, 'index.html')

def main_return(request):
    return render(request, 'main.html')

Hongik_festival/festival/posts/templates/index.html
<h2>
    {% if user.is_authenticated %}
    {{user.username}}님 안녕하세요!
    {% else %}
    로그인해주세요!
    {% endif %}
</h2>

Hongik_festival/festival/posts/templates/my_post_list.html
<!--내가 쓴 글 -->
<div>
    {% for post in posts %}
    <h2>{{post.title}}</h2>
    <p>{{post.creator.name}}</p>
    <p>{{post.how_many}}</p>
    <p>{{post.created_at}}</p>
    <p><a href="{% url 'posts:detail' post.id %}">더 알아보기</a></p>
    <br>
    <p><a href="{% url 'posts:delete' post.id %}">삭제</a></p>
    {% endfor %}
    <p><a href="{% url 'posts:my_post_list'%}">목록보기</a></p>
</div>

Hongik_festival/festival/posts/templates/post_detail.html
<div>
    <div>
        <h2>제목 : {{post.title}}</h2>
        <p>이름 :{{post.creator.username}}</p>
        <p>몇명 :{{post.how_many}}</p>
        <p>날짜 :{{post.created_at}}</p>
        <p>내용 : {{post.text}} </p>
        {% if user == post.creator %}
        <p><a href="{% url 'posts:delete' post.id %}">삭제</a></p>
        <p><a href="{% url 'posts:update' post.id %}">수정</a></p>
        {% endif%}
        <br>
    </div>
    <div>
        <h3>
            덧글창
        </h3>
        <form method="POST" action="{% url 'posts:post_comment_create' post.id %}">
            {% csrf_token %}
            <h4>덧글 쓰기</h4>
            <input type="text", name="message", placeholder="덧글을 입력해주세요.">
            <input type = "submit" value="덧글달기"> 
        </form>
    </div>
    <div>
        {% for comment in comments %}
        <p>작성자: {{comment.creator}}</p>
        <p>덧글 내용: {{comment.message}}</p>
        <p>작성일: {{comment.created_at}}</p>
        {% if user == comment.creator %}
        <p><a href="{% url 'posts:post_comment_delete' comment.id %}">삭제</a></p>
        {% endif%}
        {% endfor %}
    </div>
    <p><a href="{% url 'posts:post_list'%}">목록보기</a></p>
</div>

Hongik_festival/festival/posts/templates/post_list.html
<a href="{% url 'posts:new'%}">글쓰기</a>
<div class="container home_text">
    {% for post in posts %}
    <h2>{{post.title}}</h2>
    <p>{{post.creator.name}}</p>
    <p>{{post.how_many}}</p>
    <p>{{post.created_at}}</p>
    <p><a href="{% url 'posts:detail' post.id %}">더 알아보기</a></p>
    <br>
    {% endfor %}
</div>

<!-- 박솔민 : 게시물 리스트 보기 + 페이지네이션 -->
<form method="GET" action="">
    {%csrf_token%}
    <br>
    인원:
    <input type="text" name="search" value="{{ search }}" />
    <br>
    <input type="submit" value="검색">
    <br>
</form>

{%if posts.has_previous%}
<a href="?page=1">First</a>
<a href="?page={{ posts.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">previous</a>
{%endif%}

<span>{{posts.number}}</span>
<span>of</span>
<span>{{posts.paginator.num_pages}}</span>

{%if posts.has_next%}
<a href="?page={{posts.next_page_number}}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">Next</a>
<a href="?page={{posts.paginator.num_pages}}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">Last</a>
{%endif%}

Hongik_festival/festival/posts/templates/post_new.html
{% if post %}
<div>
<h1>글 수정하기</h1>
    <form method="POST" action="{% url 'posts:update' post.id %}">
        {% csrf_token %}
        <h4>제목 : </h4>
        <input type ="text" value="{{post.title}}" name = "title" required="true">
        <br>
        <h4>몇명 : (1 - 5까지)</h4>
        <input type="number" value="{{post.how_many}}" name="how_many" min="1" max="5" required="true">
        <h4>본문 : </h4>
        <textarea cols=40 rows=10 name="text" required="true">{{post.text}}</textarea>
        <br>
        <input type = "submit" value="제출하기"> 
    </form>
</div>
{% else %}
<div>
<h1>글 쓰기</h1>
    <form method="POST" action="{% url 'posts:new' %}">
        {% csrf_token %}
        <h4>제목 : </h4>
        <input type ="text" name = "title" required="true">
        <br>
        <h4>몇명 : (1 - 5까지)</h4>
        <input type="number" name="how_many" min="1" max="5" required="true">
        <h4>본문 : </h4>
        <textarea cols=40 rows=10 name="text" required="true"> </textarea>
        <br>
        <input type = "submit" value="제출하기"> 
    </form>
</div>
{% endif %}
<div>
    <p><a href="{% url 'posts:post_list'%}">글쓰기 취소</a></p>
</div>

<!-- 미팅 글쓰기
<p><a href="{% url 'posts:post_list'%}">돌아가기</a></p>

{% if post.title == 'admin12345' %}
    <form action="{% url 'posts:create' %}">
        <h4>제목 : </h4>
            <input type ="text" name = "title" required="true">
            <br>
            <br>
        <h4>몇명 : (1 - 5까지)</h4>
            <input type="number" name="how_many" min="1" max="5" required="true">
        <h4>본문 : </h4>
            <textarea cols=40 rows=10 name="text" required="true"> </textarea>
            <br>
            <br>
            <input class = "btn btn-dark" type = "submit" value="제출하기"> 
    </form>
    {% else %}
    <h1> 수정하기</h1>
    <form action="{% url 'posts:update' post.id %}">
        <h4>제목 : </h4>
            <input type ="text" value="{{post.title}}" name = "title" required="true">
            <br>
            <br>
        <h4>몇명 : (1 - 5까지)</h4>
            <input type="number" value="{{post.how_many}}" name="how_many" min="1" max="5" required="true">
        <h4>본문 : </h4>
            <textarea cols=40 rows=10 name="text" required="true" >{{post.text}} </textarea>
            <br>
            <br>
            <input class = "btn btn-dark" type = "submit" value="제출하기"> 
    </form>
{% endif %} -->