Hongik_festival/festival/bars/urls.py
from django.urls import path
from . import views


app_name = 'bars'
urlpatterns = [
    path('', views.bar_list, name='bar_list'),
    path('<int:bar_id>/detail/', views.bar_detail, name='bar_detail'),
    path('<int:bar_id>/likes/', views.bar_like, name='bar_like'),
]

Hongik_festival/festival/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts import views


urlpatterns = [
    path('', views.index_return, name='index'),
    path('bars/', include('bars.urls', namespace='bars')), 
    path('posts/', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hongik_festival/festival/bars/models.py
from django.conf import settings
from django.db import models
from posts.models import TimeStampedModel


class Bar(TimeStampedModel):
    """ Bar Model """
    name = models.CharField(max_length=80)
    represent_image = models.ImageField(upload_to='bars')
    first_image = models.ImageField(upload_to='bars')
    second_image = models.ImageField(upload_to='bars')
    third_image = models.ImageField(upload_to='bars')
    text = models.TextField(max_length=200) # 술집에 대한 간단한 소개
    location_url = models.TextField(max_length=200) # 술집 위치 -> 이후 필요에 따라 변경될 가능성이 높은 필드

    @property
    def barlike_count(self):
        return self.likes.count()

    def __str__(self):
        return f'{self.name}'

# 입시 모델 - 필요에 따라 삭제될 수 있는 모델
class BarLike(TimeStampedModel):
    """ BarLike Model """
    bar = models.ForeignKey(Bar, on_delete=models.CASCADE, related_name='likes')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.bar.name}-{self.creator.name}'
    

Hongik_festival/festival/bars/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from .models import Bar, BarLike


def bar_list(request):
    bars = Bar.objects.all()
    return render(request, 'bar_list.html', {'bars':bars})

@login_required
def bar_detail(request, bar_id):
    bar = get_object_or_404(Bar, id=bar_id)
    return render(request, 'detail.html', {'bar' : bar})

@login_required
def bar_like(request, bar_id):
    user = request.user
    bar = get_object_or_404(Bar, id=bar_id)
    try:
        preexisiting_like = BarLike.objects.get(creator=user, bar=bar)
        preexisiting_like.delete()
        return redirect('/bars/')
    except BarLike.DoesNotExist:
        bar_like = BarLike()
        bar_like.bar = bar
        bar_like.creator = user
        bar_like.save()
        return redirect('/bars/')
    return redirect('/bars/')

Hongik_festival/festival/bars/templates/bar_list.html
<!doctype html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap 4</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
        <style>
            p { margin:20px 0px; }
            .right-box {
                float : right;
            }
            .span {
                width: 100%;
                line-height: 500%;
                display: block;
                text-align: center;
                font-size : 20pt;
                font-family: 'Do Hyeon', sans-serif;
            }            
            .img-overlay-height{
                height: 80%;
            }
        </style>
    </head>
  <body>
    <header>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<div class="container">
        <div class="row">
            {% for bar in bars %}
                <div class="col-3">
                    <br></br>
                    <div class="card">
                        <div class="card-img-overlay img-overlay-height">
                            <h5 class="card-title span">{{bar.name}}</h5>
                        </div>
                        <a href = "{% url 'bars:bar_detail' bar.id %}" ><img src= "{{bar.represent_image.url}}" height = "200vh" style ="opacity:0.6" alt="{{bar.title}}" class = "card-img-top" /></a>
                        <div class="card-body">
                            <p class="card-text">{{bar.text}}</p>
                            <a href="{% url 'bars:bar_like' bar.id %}"><div class="btn btn-primary">좋아요</div></a>
                            <div class = 'right-box'>{{bar.barlike_count}} likes</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
</div>

</body>

</html>

Hongik_festival/festival/bars/templates/detail.html
<div class="container home_text">
    <img src="{{bar.first_image.url}}" alt="{{bar.title}}">
    <img src="{{bar.second_image.url}}" alt="{{bar.title}}">
    <img src="{{bar.third_image.url}}" alt="{{bar.title}}">
    <p>{{bar.name}}</p>
    <p>{{bar.text}}</p>
    <p>좋아요 : {{bar.barlike_count}}</p>
    <p><a href="{{bar.location_url}}">네이버 지도</a></p>   
    <br>
</div>