Hongik_festival/festival/bars/urls.py
from django.urls import path
from . import views


app_name = 'bars'
urlpatterns = [
    path('', views.bar_list, name='bar_list'),
    path('<int:bar_id>/detail/', views.bar_detail, name='bar_detail'),
    path('<int:bar_id>/likes/', views.bar_like, name='bar_like'),
]

Hongik_festival/festival/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts import views


urlpatterns = [
    path('', views.index_return, name='index'),
    path('bars/', include('bars.urls', namespace='bars')), 
    path('posts/', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hongik_festival/festival/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'users'
urlpatterns = [
    path('', views.user_list, name='user_list'),
    path('<int:user_id>/', views.userpage, name='userpage'),
    path('<int:user_id>/likes/', views.like_user, name='like_user'),
    path('mypage/', views.mypage, name='mypage'),
    path('signup/', views.signup, name='signup'),
    path('login/direct/', views.direct_login, name='direct_login'),
    path('login/indirect/', views.indirect_login, name='indirect_login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_id>/letters/', views.letter_post, name='letter_post'),
    path('letters/<str:type>/', views.letter_list, name='letter_list'),
    path('<int:letter_id>/letters/detail/', views.letter_detail, name='letter_detail'), 
    path('<int:letter_id>/letters/delete/', views.letter_to_delete, name='letter_delete'),
    path('user_male/', views.user_male, name='user_male'), 
    path('user_female/', views.user_female, name='user_female'), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hongik_festival/festival/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import models
from posts.models import TimeStampedModel


class User(AbstractUser):
    """ User Model """
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    profile_image = models.ImageField(
        upload_to='profile_images',
        blank=True,     #필드가 폼에서 빈채로 저장되는것 허용
        null=True       #필드 값이 NULL로 저장되는것 허용
        )
    name = models.CharField(max_length=140, blank=False)
    phone = models.CharField(max_length=225, blank=False) 
    bio = models.TextField(blank=True, null=True)
    gender = models.CharField(max_length=80, choices=GENDER_CHOICES, null=True)
    profile_open = models.BooleanField(default=True)

    @property
    def userlike_count(self):
        return self.userlike_to.count()
    
    @property
    def post_count(self):
        return self.posts.count()

    def __str__(self):
        return self.username


class UserLike(TimeStampedModel):
    """  UserLike Model"""
    userlike_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        null=True, 
        related_name='userlike_to'
        ) # 유저 좋아요 받는 대상 유저
    userlike_from = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.PROTECT, 
        null=True,
        ) # 유저 좋아요 보내는 유저

    def __str__(self):
        return f'{self.userlike_to.id}-{self.userlike_from.id}'


class Letter(TimeStampedModel):
    """ Letter Model """
    letter_to = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.SET_DEFAULT,
        null=True, 
        default='알수없음', 
        related_name='letter_to'
        )
    letter_from = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.SET_DEFAULT, 
        null=True, 
        default='알수없음',
        related_name='letter_from'
        )
    text = models.TextField(null=True)
    check = models.BooleanField(default=False)
    delete = models.BooleanField(default=False) 
    # 쪽지함에서 삭제(실제로 디비에서 삭제되는 것이 아닌 목록에 띄우지 않는 것임)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f'{self.letter_to.name}-{self.letter_from.name}'

Hongik_festival/festival/users/forms.py
from django import forms
from .models import Letter


# Letter을 기반으로 한 Form
class LetterPost(forms.ModelForm):
    class Meta:
        model = Letter
        fields = [
            'text',
        ]

Hongik_festival/festival/users/views.py
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from .models import User, Letter, UserLike
from .forms import LetterPost


# 마이페이지 보기 - 수정
@login_required
def mypage(request):
    user = request.user
    # 받은 쪽지 개수
    letter_to = Letter.objects.filter(letter_to=request.user, delete=False).count()
    # 보낸 쪽지 개수
    letter_from = Letter.objects.filter(letter_from=request.user, delete=False).count()
    return render(request, 'mypage.html', {
        'user':user, 
        'letter_to':letter_to,
        'letter_from':letter_from
    })

# 타유저의 페이지 보기
@login_required
def userpage(request, user_id):
    user = User.objects.get(id=user_id)
    return render(request, 'userpage.html', {'user':user})
 
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                username=request.POST['username'],
                name=request.POST.get('name'), 
                password=request.POST['password1'], 
                profile_image=request.FILES.get('profile_img', None),
                bio=request.POST['bio'],
                phone=request.POST['phone'], 
                gender=request.POST['gender'], 
                profile_open=request.POST['profile_open'],
                )
            if user is not None:
                auth.login(request, user)
                return redirect('/users/mypage/')
    print("회원가입 안됨")
    return render(request, 'signup.html') 

# 로그인을 하지 않은 상태에서 로그인이 필요한 서비스를 이용하고자 할때
def indirect_login(request):
    if request.method == 'GET':
        # 처음 로그인 요청이 들어왔던 페이지 경로를 global 변수에 넣음
        global redirect_url
        redirect_url = request.GET.get('next')
        error_message = '로그인이 필요한 서비스입니다. 로그인해주세요.'
        return render(request, 'login.html', {'error_message':error_message})
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user) 
            return redirect(redirect_url)# 처음 요청이 들어왔던 페이지로 다시 리다이렉트(동적으로 변함)
        else:
            error_message = '일시적인 오류로 다시 로그인해주세요.'
            return render(request, 'login.html', {'error_message':error_message})
    error_message = '잘못된 요청입니다. 다시 로그인해주세요.'  
    return render(request, 'login.html', {'error_message':error_message})

# 로그인 페이지에서 로그인 할 때
def direct_login(request):
    if request.method == 'GET':
        error_message = '로그인페이지입니다.'
        return render(request, 'login.html', {'error_message':error_message})
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)        
        if user is not None:
            auth.login(request, user)
            return render(request, 'index.html', {'user':user})
    error_message = '잘못된 요청입니다. 다시 로그인해주세요.'  
    return render(request, 'login.html', {'error_message':error_message})
        
@login_required
def logout(request):
    auth.logout(request)
    return redirect('/')

# 쪽지 보내기
@login_required
def letter_post(request, user_id):
    if request.user.is_authenticated and request.method == 'POST':
        form = LetterPost(request.POST)
        if form.is_valid():
            letter = form.save(commit=False)
            letter.letter_to = get_object_or_404(User, id=user_id)
            letter.letter_from = request.user
            letter.save()
            return redirect('/users/letters/from/')
    elif request.method == 'GET':
        letter_to = get_object_or_404(User, id=user_id)
        form = LetterPost()
        return render(request, 'letter_post.html', {'form':form, 'letter_to':letter_to})

# 받은 쪽지 보기(type='to') / 보낸 쪽지 보기(type='from')
@login_required
def letter_list(request, type):
    if type == 'to':
        letter_to_list = Letter.objects.filter(letter_to=request.user, delete=False)
        return render(request, 'letter_list.html', {'letters':letter_to_list})
    elif type == 'from':
        letter_from_list = Letter.objects.filter(letter_from=request.user, delete=False)
        return render(request, 'letter_list.html', {'letters':letter_from_list})
 
@login_required
def letter_to_delete(request, letter_id):
    user = request.user
    letter = get_object_or_404(Letter, id=letter_id)
    letter.delete = True
    letter.save()
    if letter.letter_to == user: 
        return redirect('/users/letters/to/')
    elif letter.letter_from == user:
        return redirect('/users/letters/from/')

# 쪽지 상세보기
@login_required
def letter_detail(request, letter_id):
    user = request.user
    letter = Letter.objects.get(id=letter_id)
    letter.check = True
    letter.save()
    return render(request, 'letter_detail.html', {'letter':letter, 'user':user})

# 유저 목록 (성별에 따른 검색 기능)
def user_list(request):
    users_all = User.objects.filter(profile_open=True)
    paginator = Paginator(users_all, 5)
    page = request.GET.get('page')
    users_list = paginator.get_page(page)
    return render(request, 'user_list.html', {'users_list':users_list})

def user_male(request):
    users_find = User.objects.filter(gender='male', profile_open=True)
    paginator = Paginator(users_find, 5)
    page = request.GET.get('page')
    users_list = paginator.get_page(page)
    return render(request, 'user_list.html', {'users_list':users_list})

def user_female(request):
    users_find = User.objects.filter(gender='female', profile_open=True)
    paginator = Paginator(users_find, 5)
    page = request.GET.get('page')
    users_list = paginator.get_page(page)
    return render(request, 'user_list.html', {'users_list':users_list})


# 유저에게 하트 보내기
@login_required
def like_user(request, user_id):
    user = request.user
    like_user = get_object_or_404(User, id=user_id)
    try:
        preexisiting_like = UserLike.objects.get(userlike_from=user, userlike_to=like_user)
        preexisiting_like.delete()
        return redirect('/users/' + str(like_user.id))
    except UserLike.DoesNotExist:
        userlike = UserLike()
        userlike.userlike_to = like_user
        userlike.userlike_from = user
        userlike.save()
        return redirect('/users/' + str(like_user.id))

Hongik_festival/festival/users/templates/home.html
home

Hongik_festival/festival/users/templates/letter_detail.html
<!--쪽지 상세 페이지입니다.-->
<div>
    <p>To: {{letter.letter_to}}</p>
    <p>From: {{letter.letter_from}}</p>
    <p>내용: {{letter.text}}</p>
    <p>확인여부: {{letter.check}}</p>
    <p>{{letter.created_at}}</p>
    <br>
</div>

{% if user == letter.letter_to %}
<a href="{% url 'users:letter_post' user_id=letter.letter_from.id %}">답장하기</a>
{% endif %}
<!--삭제하기 전에 정말 삭제하시겠습니까? 확인메시지 뜨면 좋을것 같아요-->
<a href="{% url 'users:letter_delete' letter.id %}">삭제하기</a>

Hongik_festival/festival/users/templates/letter_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="./style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--    메터리얼라이즈-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<!--    <script type="text/javascript" src="./script.js"></script>-->
    <script>
      $(document).ready(function(){
        $('.sidenav').sidenav();
      });
    </script>
    <style>
        .brand-logo img{
    width: 30vw;
}

@media(max-width: 600px){
    
    
    .brand-logo img{width: 60vw;}
    .collection{}
    .collection-item{margin: 5% 5%;}
    
    #materialize-overrides .title_sub{
    border-radius: 80px;
    padding: 0 5vw;
    margin: 3vw 0 3vw 2vw;
    }    

    #materialize-overrides .title{
    margin-top: 5vw;
    }    
    .secondary-content{
/*    font-size: 1em;*/
    }
    
    #materialize-overrides .pagination{
    margin-top: 15vw;        
    }
    
    #materialize-overrides .material-icons{
        margin-top: 1vw;
        font-size: 26px;
    }
    
    #materialize-overrides .cancel{
        margin-left: 50vw;
    }
    
    #materialize-overrides .heart{
        margin-left: 12vw;
    }
    
    </style>
</head>
<body id="materialize-overrides">
<!--   헤더-->
 
  <nav>
    <div class="nav-wrapper pink">
      <a href="#!" class="brand-logo"><img src="./img/logo.png" alt=""></a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger">
          <i class="material-icons">menu</i>
        </a>
        <ul class="right hide-on-med-and-down">
            <li><a href="sass.html">미팅</a></li>
            <li><a href="badges.html">1대1쪽지보내기</a></li>
            <li><a href="collapsible.html">홍대술집</a></li>
            <li><a href="mobile.html">신고하기</a></li>
          </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">미팅</a></li>
    <li><a href="badges.html">1대1쪽지보내기</a></li>
    <li><a href="collapsible.html">홍대술집</a></li>
    <li><a href="mobile.html">신고하기</a></li>
  </ul>
  
<!--   타이틀-->          
    <a class="title_sub waves-effect waves-light btn-small pink"><b>쪽지함</b></a>
    
<!--   리스트-->
    <ul class="collection">
    <li class="collection-item avatar">
     <img src="./img/main_left.png" alt="" class="circle">
      <span class="title">안현준</span>
      <p>2대2미팅입니다~2대2미팅입니다~2대2미팅입니다~
      </p>
      <a href="#!" class="secondary-content"><i>남자24</i></a>
    </li>
    <li class="collection-item avatar">
      <img src="./img/main_left.png" alt="" class="circle">
      <span class="title">안현준</span>
      <p>2대2미팅입니다~2대2미팅입니다~2대2미팅입니다~
      </p>
      <a href="#!" class="secondary-content"><i>남자24</i></a>
    </li>
    <li class="collection-item avatar">
     <img src="./img/main_left.png" alt="" class="circle">
      <span class="title">안현준</span>
      <p>2대2미팅입니다~2대2미팅입니다~2대2미팅입니다~
      </p>
      <a href="#!" class="secondary-content"><i>남자24</i></a>
    </li>
    <li class="collection-item avatar">
     <img src="./img/main_left.png" alt="" class="circle">
      <span class="title">안현준</span>
      <p>2대2미팅입니다~2대2미팅입니다~2대2미팅입니다~
      </p>
      <a href="#!" class="secondary-content"><i>남자24</i></a>
    </li>
  </ul>

<a class="title_sub waves-effect waves-light btn-large pink"><b>보내기</b></a>
<a class="title_sub waves-effect waves-light btn-large pink cancel"><b>취소하기</b></a>    
<!--페이지네이션입니다  -->
 <ul class="pagination center-align">
<!--    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>-->
    <li class="active pink"><a href="#!">1</a></li>
    <li class="waves-effect"><a href="#!">2</a></li>
    <li class="waves-effect"><a href="#!">3</a></li>
    <li class="waves-effect"><a href="#!">4</a></li>
    <li class="waves-effect"><a href="#!">5</a></li>
<!--    <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>-->
  </ul>
     
</body>
</html>

Hongik_festival/festival/users/templates/letter_post.html
<!--쪽지를 작성하는 페이지입니다.-->
<div>
    <form method="POST" action="{% url 'users:letter_post' letter_to.id%}">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <br>
        <input class="btn btn-primary" type="submit" value="Submit!">
    </form>
</div>

Hongik_festival/festival/users/templates/login.html
{% if error_message %}
<h2>{{error_message}}</h2>
{% endif %}
<form method="POST" action="{% url 'users:login' %}">
    {%csrf_token%}
    Username:
    <br>
    <input name="username" type="text" value="">
    <br>
    Password:
    <br>
    <input name="password" type="password" value="">
    <br>
    <br>
    <input class="btn btn-primary" type="submit" value="Login">
</form>

Hongik_festival/festival/users/templates/mypage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="./style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--    메터리얼라이즈-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<!--    <script type="text/javascript" src="./script.js"></script>-->
    <script>
      $(document).ready(function(){
        $('.sidenav').sidenav();
      });
    </script>
    <style>
      .brand-logo img{
    width: 30vw;
}

@media(max-width: 600px){
    
    
    .brand-logo img{width: 60vw;}
    .collection{}
    .collection-item{margin: 5% 5%;}
    
    #materialize-overrides .title_sub{
    border-radius: 80px;
    padding: 0 5vw;
    margin: 3vw 0 3vw 2vw;
    }    

    #materialize-overrides .title{
    margin-top: 5vw;
    }    
    .secondary-content{
/*    font-size: 1em;*/
    }
    
    #materialize-overrides .pagination{
    margin-top: 15vw;        
    }
    
    #materialize-overrides .material-icons{
        margin-top: 1vw;
        font-size: 26px;
    }
    
    #materialize-overrides .cancel{
        margin-left: 50vw;
    }
    
    #materialize-overrides .heart{
        margin-left: 12vw;
    }


    </style>
</head>
<body id="materialize-overrides">
<!--   헤더-->
 
  <nav>
    <div class="nav-wrapper pink">
      <a href="#!" class="brand-logo"><img src="./img/logo.png" alt=""></a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger">
          <i class="material-icons">menu</i>
        </a>
        <ul class="right hide-on-med-and-down">
            <li><a href="sass.html">미팅</a></li>
            <li><a href="badges.html">1대1쪽지보내기</a></li>
            <li><a href="collapsible.html">홍대술집</a></li>
            <li><a href="mobile.html">신고하기</a></li>
          </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">미팅</a></li>
    <li><a href="badges.html">1대1쪽지보내기</a></li>
    <li><a href="collapsible.html">홍대술집</a></li>
    <li><a href="mobile.html">신고하기</a></li>
  </ul>
  
<!--   타이틀-->          
    <a class="title_sub waves-effect waves-light btn-small pink"><b>마이페이지</b></a>
    
<!--컨텐츠    -->
    <div class="row">
    <div class="col s12 m6">
      <div class="card">
        <div class="card-image">
          <img src="./img/index_1.png" alt="" class="circle">
          <h3 class="center-align"><b>안현준</b></h3>
        </div>
        <!--버튼-->
        <a class="title_sub waves-effect waves-light btn-large pink"><b>쪽지함</b></a>
        <a class="title_sub waves-effect waves-light btn-large blue"><b>12</b></a>
        <a class="title_sub waves-effect waves-light btn-large pink heart"><b>하트함</b></a>
        <a class="title_sub waves-effect waves-light btn-large blue"><b>12</b></a>
      </div>
    </div>
  </div>
</body>
</html>

Hongik_festival/festival/users/templates/signup.html
<div>
    <form method="POST" action="{% url 'users:signup'%}" enctype="multipart/form-data">
        {%csrf_token%}
        아이디:
        <br>
        <input type="text", name="username">
        <br>
        회원 이름:
        <br>
        <input type="text", name="name">
        <br>
        핸드폰 번호:
        <br>
        <input type="text", name="phone">
        <br>
        Password:
        <br>
        <input name="password1" type="password" value="">
        <br>
        Confirm Password:
        <br>
        <input name="password2" type="password" value="">
        <br>
        <input type='radio' name='gender' value='female' />여성
        <input type='radio' name='gender' value='male' />남성
        <br>
        간단한 자기소개:
        <input type="text" name="bio">
        <br>
        프로필이미지:
        <input type="file" name="profile_img">
        <br>
        <br>
        <input type='radio' name='profile_open' value='True' />공개
        <input type='radio' name='profile_open' value='False' />비공개
        <br>
        <input class="btn btn-primary" type="submit" value="회원가입">
    </form>
</div>

Hongik_festival/festival/users/templates/user_female.html
<!--모든 회원 목록을 볼 수 있는 페이지입니다.-->
{% load static %}
{% for user in users_list %}
<div>
    <p>{{user.username}}</p>
    <p>{{user.gender}}</p>
    <p>{{bar.bio}}</p>
    <br>
</div>
{% endfor %}

<br><br><br>






{%if users_list.has_previous%}
<a href="?page=1">First</a>
<a href="?page={{users_list.previous_page_number}}">Previous</a>
{%endif%}

<span>{{users_list.number}}</span>
<span>of</span>
<span>{{users_list.paginator.num_pages}}</span>

{%if users_list.has_next%}
<a href="?page={{users_list.next_page_number}}">Next</a>
<a href="?page={{users_list.paginator.num_pages}}">Last</a>
{%endif%}

<br>
<br>
<br>

<a href="./">전체</a>

<a href="user_male">남자</a>

<a href="user_female">여자</a>

Hongik_festival/festival/users/templates/user_list.html
<!--모든 회원 목록을 볼 수 있는 페이지입니다.-->

{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body id="bootstrap-overrides">
        <nav class="navbar navbar-expand-lg navbar-light">
                <a class="navbar-brand" href="#"><img id="main-logo" src="{% static 'img/logo.png' %}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#"> 미팅 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">1대1쪽지보내기</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">홍대술집</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">신고하기</a>
                    </li>
                    <li class="nav-item">
                        <a class="person_part" href="#"><img id="person_img" src="{% static 'img/mypage.png' %}" alt=""></a>
                    </li>
                    </ul>
                </div>               
        </nav>
        <div id="container">
            <div class="user_list_txt">
            {% for user in users_list %}
            <a href="{% url 'users:userpage' user.id %}">
                <div class="message">
                    <img class="profile" src="{{ user.profile_image.url }}" alt="{{user.username}}" width="240px" >
                        <div class="name">
                            <p class="name_name">{{user.username}}</p>
                            <p class="name_text">{{user.bio}}</p> 
                        </div>
                        <div class="sec">
                            <p class="age"> {{user.gender}}</p>
                        </div>
            {% endfor %}
                </div>
            </a>
            </div>
        </div>
    </body>
</html>
<br>
<br>
<br>

{%if users_list.has_previous%}
<a href="?page=1">First</a>
<a href="?page={{users_list.previous_page_number}}">Previous</a>
{%endif%}

<span>{{users_list.number}}</span>
<span>of</span>
<span>{{users_list.paginator.num_pages}}</span>

{%if users_list.has_next%}
<a href="?page={{users_list.next_page_number}}">Next</a>
<a href="?page={{users_list.paginator.num_pages}}">Last</a>
{%endif%}
<br>
<a href="{% url 'users:user_list' %}">전체</a>
<a href="{% url 'users:user_male' %}">남자</a>
<a href="{% url 'users:user_female' %}">여자</a>
<br>
<br>

Hongik_festival/festival/users/templates/user_male.html
<!--모든 회원 목록을 볼 수 있는 페이지입니다.-->
{% load static %}
{% for user in users_list %}
<div>
    <p>{{user.username}}</p>
    <p>{{user.gender}}</p>
    <p>{{bar.bio}}</p>
    <br>
</div>
{% endfor %}

<br><br><br>



{%if users_list.has_previous%}
<a href="?page=1">First</a>
<a href="?page={{users_list.previous_page_number}}">Previous</a>
{%endif%}

<span>{{users_list.number}}</span>
<span>of</span>
<span>{{users_list.paginator.num_pages}}</span>

{%if users_list.has_next%}
<a href="?page={{users_list.next_page_number}}">Next</a>
<a href="?page={{users_list.paginator.num_pages}}">Last</a>
{%endif%}

<br>
<br>
<br>


<a href="./">전체</a>

<a href="user_male">남자</a>

<a href="user_female">여자</a>

Hongik_festival/festival/users/templates/userpage.html
<h2>{{user.username}}님의 페이지</h2>
<br>
<img src="{{ user.profile_image.url }}" width="240px" alt="">
<br>
{{user.username}}
<br>
{{user.gender}}
<br>
{{user.bio}}
<br>
하트 개수:
{{user.userlike_count}}
<br>

{% if user.is_authenticated %}
<a href="{% url 'users:letter_post' user_id=user.id %}">쪽지보내기</a>
<br>
<a href="{% url 'users:like_user' user_id=user.id %}">하트 보내기</a>
{% endif %}